spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.92.1:3306/backend?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  quartz:
    auto-startup: true
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    properties: # 添加 Quartz Scheduler 附加属性
      org:
        quartz:
          scheduler:
            # scheduler的实例名
            instanceName: scheduler
            instanceId: AUTO
          threadPool:
            threadCount: 10 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 表示数据库中相关表是QRTZ_开头的
            tablePrefix: QRTZ_
            useProperties: false


server:
  port: 8088

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.wbazmy.backend.constant.enums

file:
  python-path: /bin/python3
  python-file-path: /home/uu/WorkSpace/code/main.py
  history-data-path: /home/uu/WorkSpace/history-data/
  project-path: /home/uu/WorkSpace/expproject/
  upload-path: /home/uu/WorkSpace/expproject/
  check-data-path: /home/uu/WorkSpace/tmp/

git:
  mirror-url: hub.yzuu.cf